# use java support
language: java
jdk: openjdk11

before_install:
  
  - sudo apt update
  - sudo apt install maven
  - sudo apt install openjfx
  - sudo apt install mysql-workbench

# Install xmlstarlet
addons:
  apt:
    packages:
      - xmlstarlet
      - ant
      - build-essential


  sonarcloud:
    organization: "evoi95"
    token:
      secure: "042e971071e1b954c2ca87301f32f6abe68fc20c" # encrypted value of your token


# Do not run travis install step
install: true
 
cache:
  directories:
    - $HOME/.m2  
 
services:
  - mysql
   
script:
    - mvn clean install
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Evoi95_BSO-Maven
    - mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - ant build
