# use java support
language: java
jdk: openjdk11

before_install:
  
  - sudo apt update
  - sudo apt install maven
  - sudo apt install openjfx
  - sudo apt install mysql-workbench
  - sudo apt install libjacoco-java


# Install xmlstarlet
addons:
  apt:
    packages:
      - xmlstarlet
  sonarcloud:
    organization: "evoi95"
    token:
      secure: "3c2f7e5cb9b0b7cf6c9bc0dc05120ca054fb0730" # encrypted value of your token

    
# Do not run travis install step
install: true
 
cache:
  directories:
    - $HOME/.m2  
 
services:
  - mysql
   
script:
    - mvn clean compile verify
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Evoi95_BSO-Maven
    - ant build
