# use java support
language: java
jdk: openjdk11

# run in container
sudo: false

before_install:
  
  - sudo apt update
  - sudo apt install maven
  - sudo apt install openjfx
  - sudo apt install mysql-workbench

# Install xmlstarlet
addons:
  apt:
    packages:
      - xmlstarlet

# Do not run travis install step
install: true
 
cache:
  directories:
    - $HOME/.m2  
 
services:
  - mysql
    xvfb

script:
    - mvn clean compile verify

    - ant build