# use java support
language: java
jdk: openjdk11

# run in container
sudo: false


# configure xvfb screen
services:
  - xvfb

# Install xmlstarlet
addons:
  apt:
    packages:
      - xmlstarlet

# Do not run travis install step
install: true

# Assemble jars
script:
  ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  - mvn clean compile verify

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - sudo apt install mysql-workbench
  
  
cache:
  directories:
    - $HOME/.m2  
 
services:
  - mysql

script:
  - ant build