package boundary.laptop;

public enum BookCategory {
	ADOLESCENTI_RAGAZZI, ARTE, CINEMA_FOTOGRAFIA,BIOGRAFIE,DIARI_MEMORIE, CALENDARI_AGENDE,DIRITTO,
	DIZINARI_OPERE, ECONOMIA,FAMIGLIA, SALURE_BENESSERE, FANTASCIENZA_FANTASY,FUMETTI_MANGA,GIALLI_THRILLER,SELFHELP,COMPUTER_GIOCHI,
	HUMOR,INFORMATICA,WEB_DIGITAL_MEDIA,LETTERATURA_NARRATIVA,LIBRI_BAMBINI,LIBRI_SCOLASTICI,	LIBRI_UNIVERSITARI,RICETTARI_GENERALI,
	LINGUISTICA_SCRITTURA,POLITICA,RELIGIONE,ROMANZI_ROSA,SCIENZE,TECNOLOGIA_MEDICINA,SPORT,STORIA, TEMPO_LIBERO,VIAGGI,ALTRO
	

}
