package boundary.laptop;

public enum MagazineCategory {
	SETTIMANALE,BISETTIMANALE,MENSILE,
	BIMESTRALE,TRIMESTRALE,ANNUALE,
	ESTIVO,INVERNALE,SPORTIVO,CINEMATOGRAFICA,
	GOSSIP,TELEVISIVO,MILITARE,INFORMATICA

}
